-- idempotency_keys: the durable half of `Idempotency-Key` handling on every
-- POST under `/v1` (docs/api/README.md; the header is REQUIRED, not
-- optional, per this step's D7).
--
-- The primary key IS the mutual exclusion, exactly as
-- `oauth_client_assertion_jtis` (migration 0011) is for assertion replay:
-- `vpay_db::idempotency::claim` runs one
-- `INSERT ... ON CONFLICT (merchant_id, idempotency_key) DO UPDATE
--  ... WHERE idempotency_keys.expires_at < now() RETURNING claim_id` and
-- reads whether a row came back. The `DO UPDATE` arm is what makes an
-- *expired* row reclaimable rather than locking the key out forever; it is
-- guarded so it can never fire for a live one. A row means this
-- process owns the key and must do the work; no row means someone else
-- claimed it first, and only then does a SELECT decide whether that other
-- request is still running (`in_flight`), already answered (`complete`, so
-- replay its stored response), or a *different* request wearing the same
-- key (a hash mismatch → 400 `idempotency_key_in_use`). Never
-- check-then-insert as two statements: two simultaneous retries of the same
-- POST would both observe "not claimed" and both charge the payer.
--
-- The key is scoped per merchant, not globally: an `Idempotency-Key` is
-- chosen by a merchant's own client library and two merchants picking the
-- same UUID must not collide. `merchant_id` leads the primary key so the
-- lookup is a single index probe on the composite.
CREATE TABLE idempotency_keys (
    -- No FK, for the same reason payment_intents.merchant_id has none:
    -- there is no `merchants` table (ADR-0003 keeps merchant identity in
    -- YAML). See 0003's own comment.
    merchant_id TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    -- Which *claim* owns this row right now, regenerated every time the row
    -- is claimed afresh (`vpay_db::idempotency::claim`'s `DO UPDATE` arm
    -- sets it, the INSERT arm takes the default).
    --
    -- The primary key alone is not enough to identify a claim, because a
    -- row is reclaimable once `expires_at` has passed: request R1 claims
    -- the key, stalls for more than 24 hours, R2 reclaims the same row —
    -- and R1 then wakes up. Addressed by `(merchant_id, idempotency_key)`
    -- plus `state = 'in_flight'` alone, R1's release would DELETE R2's live
    -- claim and R1's store would overwrite R2's row with R1's response:
    -- classic ABA, and the payload here is a payment response a merchant
    -- would be handed for a request they did not make. `store` and
    -- `release` therefore both carry `AND claim_id = $n`, so a claim that
    -- is no longer the current one matches nothing.
    --
    -- Generated by the database rather than by Rust so that the value is
    -- minted by the same statement that wins the claim; a Rust-side uuid
    -- passed into the INSERT would be discarded by the `DO UPDATE` arm
    -- unless it were bound a second time, which is one more place for the
    -- two arms to disagree. `gen_random_uuid()` is core Postgres since 13
    -- (no pgcrypto extension); this deployment runs 16.
    claim_id UUID NOT NULL DEFAULT gen_random_uuid(),
    -- Method and path are stored for operators and for the request-hash
    -- audit trail, not read by the claim logic: the hash below already
    -- covers both (vpay-api computes SHA-256 over method + path + raw
    -- body), so comparing them again would be redundant. They exist so
    -- "what request was this key used for" is answerable from the row
    -- alone, without reversing a hash.
    request_method TEXT NOT NULL,
    request_path TEXT NOT NULL,
    -- SHA-256 of the request, as raw bytes. BYTEA rather than hex TEXT so
    -- the length CHECK is meaningful and the comparison in Rust is over
    -- bytes (done in constant time — see `vpay_db::idempotency::claim`).
    request_hash BYTEA NOT NULL,
    state TEXT NOT NULL,
    -- The response to replay. SMALLINT holds any HTTP status; the body is
    -- the exact JSON that was sent, so a replay is byte-equivalent rather
    -- than re-rendered from the current code (which may since have
    -- changed).
    response_status SMALLINT,
    response_body JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    -- Stripe's own window, and the one docs/api/README.md documents: a key
    -- is remembered for 24 hours. The default is computed at insert time
    -- rather than derived in a query so a sweep is a plain indexed
    -- `expires_at < now()` scan.
    expires_at TIMESTAMPTZ NOT NULL DEFAULT now() + INTERVAL '24 hours',

    PRIMARY KEY (merchant_id, idempotency_key),

    CONSTRAINT idempotency_key_length CHECK (char_length(idempotency_key) BETWEEN 1 AND 255),
    CONSTRAINT merchant_id_length CHECK (char_length(merchant_id) BETWEEN 1 AND 128),
    CONSTRAINT request_hash_is_sha256 CHECK (octet_length(request_hash) = 32),
    CONSTRAINT state_is_known CHECK (state IN ('in_flight', 'complete')),
    -- A `complete` row that cannot answer a replay is worse than no row at
    -- all: the second request would be told "already handled" and handed
    -- nothing. This makes that state unrepresentable.
    CONSTRAINT complete_has_a_response CHECK (
        state <> 'complete'
        OR (response_status IS NOT NULL AND response_body IS NOT NULL AND completed_at IS NOT NULL)
    )
);

-- For `vpay_db::idempotency::sweep_expired`, which is the only query that
-- does not address a row by its primary key.
CREATE INDEX idempotency_keys_expires_at_idx ON idempotency_keys (expires_at);

COMMENT ON TABLE idempotency_keys IS
    'Durable Idempotency-Key ledger for POST /v1 (D7: the header is required). The (merchant_id, idempotency_key) primary key is the atomic claim: INSERT ... ON CONFLICT DO UPDATE (guarded to expired rows only) RETURNING claim_id, then SELECT on conflict — never check-then-insert. Rows expire after 24 hours; vpay_db::idempotency::sweep_expired deletes them, and nothing schedules that call yet (the worker job loop is not started — docs/status.md), so today the table grows until an operator or a future job runs it.';
COMMENT ON COLUMN idempotency_keys.claim_id IS
    'Identifies the claim that currently owns this row, regenerated on every (re)claim. vpay_db::idempotency::store and ::release both match on it, so a request whose expired claim was taken over by a later one can neither overwrite the new response nor delete the new claim (ABA).';
COMMENT ON COLUMN idempotency_keys.request_hash IS
    'SHA-256 over method + path + raw request body, computed by vpay-api. A second request presenting the same key with a different hash is rejected as idempotency_key_in_use; the comparison is constant-time in Rust so the response cannot be used as a hash oracle.';
