//! Build script for `tauri-plugin-vpay-checkout`.
//!
//! `tauri_plugin::Builder` does three things this crate depends on, and it is
//! worth naming them because none of them is visible in `src/`:
//!
//! 1. It writes `permissions/autogenerated/commands/{show,dismiss}.toml` plus
//!    `permissions/autogenerated/reference.md` and
//!    `permissions/schemas/schema.json`, from `COMMANDS` below. Those files
//!    are **tracked**, the way `tauri-apps/plugins-workspace` tracks its own
//!    (`plugins/opener/permissions/{autogenerated,schemas}`), so that a
//!    consuming app can resolve `vpay-checkout:allow-show` from a plain
//!    checkout without first running this build script.
//! 2. It emits the `mobile` and `desktop` cfg aliases — with their
//!    `rustc-check-cfg` declarations — that `src/lib.rs` switches the host
//!    implementation on. Nothing else defines them.
//! 3. On an `android`/`ios` target only, it copies Tauri's own mobile API
//!    project into `android/.tauri/` and `./.tauri/` so the Kotlin and Swift
//!    sources of Lanes B and C can compile against it. On a desktop target
//!    both paths are ignored entirely, which is why this crate builds today
//!    with `android/` and `ios/` not yet written.
//!
//! `.build()` rather than `.try_build()`: on failure it prints the error and
//! exits non-zero, which is the correct behaviour for a build script and does
//! not need the `unwrap` that `try_build` would.

/// The two commands `src/commands.rs` exposes, and the only two the brief's
/// wire contract defines. Adding a name here without adding the matching
/// `#[tauri::command]` produces a permission for a command that does not
/// exist; removing one breaks every app whose capability file names it.
const COMMANDS: &[&str] = &["show", "dismiss"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
}
