// swift-tools-version:5.9
// The iOS host of `tauri-plugin-vpay-checkout` — Lane C of
// `docs/plans/2026-09-22-tauri-plugin-brief.md`, "The iOS host".
//
// # Why this manifest looks the way it does
//
// It is deliberately the same shape as every first-party Tauri v2 iOS
// plugin, because `tauri-plugin`'s build script and `tauri-cli`'s Xcode
// project generator both assume that shape. Verified against
// `tauri-apps/plugins-workspace@v2`'s `plugins/opener/ios/Package.swift`
// and `plugins/dialog/ios/Package.swift` (both read 2026-09-22), which are
// byte-for-byte this structure with a different name:
//
//   * package name == product name == target name == the Rust crate name,
//   * `type: .static` on the library — the generated Xcode project links
//     the plugin into the app binary; a dynamic product would need an
//     embedded framework nobody generates,
//   * `path: "Sources"` on the single target,
//   * the one dependency is `.package(name: "Tauri", path: "../.tauri/tauri-api")`.
//
// **`../.tauri/tauri-api` does not exist in this repository and must not.**
// It is written there at build time by `tauri_plugin::Builder::ios_path`
// (see this crate's `build.rs`, which calls `.ios_path("ios")`), which
// copies Tauri's own `crates/tauri/mobile/ios-api` Swift package into the
// plugin crate root — a *sibling* of this `ios/` directory. Upstream
// ignores exactly that path from its repository root
// (`/plugins/*/.tauri` in `plugins-workspace`'s `.gitignore`); this
// repository ignores it from
// `sdks/tauri/tauri-plugin-vpay-checkout/.gitignore`. Consequences worth
// knowing before you try to build this directory on its own: a bare
// `swift build` here fails at dependency resolution until something has
// produced that directory, and the `Tauri` package in turn depends on
// `github.com/Brendonovich/swift-rs`, so the first resolve needs network.
//
// # The two version floors
//
// `.iOS(.v15)`, not upstream's `.v13`, and not D-M4's original 12.0
// "widest reach" floor. Two independent reasons, the same pair the Flutter
// plugin's `Package.swift` records: Swift Concurrency (13+), and
// `sheetPresentationController`'s detent API, which
// `VpayCheckoutExternalBrowserSession` relies on for the maintainer's
// "large detent, draggable to full height" decision (D5, revised
// 2026-09-16) and which is 15.0. Tauri 2 itself builds iOS apps against a
// modern floor and does not object to a plugin raising it; it objects to a
// plugin lowering it below the app's.
//
// **This floor does not reach every compiler that builds these sources.**
// `cargo check --target aarch64-apple-ios` on the plugin crate never reads
// this manifest: it goes through `tauri_utils::build::link_apple_library` →
// `swift_rs::SwiftLinker::with_ios(…)`, which reads
// `IPHONEOS_DEPLOYMENT_TARGET` and **defaults to "13.0"**. So the sources
// under `Sources/` must still compile at `-target arm64-apple-ios13.0`, and
// every iOS-15-only API in them is wrapped in `if #available(iOS 15.0, *)`.
// See `Sources/VpayCheckoutPlugin/VpayCheckoutExternalBrowserSession.swift`
// in `present(from:)` for the one place that bites.
//
// `swift-tools-version:5.9` rather than upstream's 5.3: 5.3 predates
// `.iOS(.v15)` as a case, and nothing here needs to be resolvable by a
// Swift 5.3 toolchain — the `Package.swift` of the app that consumes this
// is generated by `tauri-cli` for whatever Xcode is installed.

import PackageDescription

let package = Package(
  name: "tauri-plugin-vpay-checkout",
  platforms: [
    .iOS(.v15)
  ],
  products: [
    .library(
      name: "tauri-plugin-vpay-checkout",
      type: .static,
      targets: ["tauri-plugin-vpay-checkout"])
  ],
  dependencies: [
    .package(name: "Tauri", path: "../.tauri/tauri-api")
  ],
  targets: [
    // `path: "Sources"` with the sources one level further down, in
    // `Sources/VpayCheckoutPlugin/`, as the brief's layout specifies.
    // Upstream keeps its one or two files flat directly under `Sources/`;
    // SwiftPM walks the whole subtree either way, so both are the same
    // target to the compiler.
    .target(
      name: "tauri-plugin-vpay-checkout",
      dependencies: [
        .byName(name: "Tauri")
      ],
      path: "Sources")
  ]
)
