[package]
name = "vpay-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
vpay-core.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
figment.workspace = true
garde.workspace = true
serde_yaml_ng.workspace = true
clap.workspace = true
tokio.workspace = true
