//! The `events` repository (`backends/migrations/0018_create-events.sql`) —
//! the durable log behind webhook fan-out and, later, `GET /v1/events`.
//!
//! # What is written here, and what is not
//!
//! This step writes an event for **terminal transitions only** (the design's
//! decision 4): `payment_intent.succeeded` and
//! `payment_intent.payment_failed`, both from
//! [`crate::settlement`]'s single settlement transaction. The milestone
//! events `docs/flows/webhooks.md` also lists —
//! `payment_intent.created`/`.processing`/`.canceled`, the two refund ones —
//! are not emitted by anything yet. Migration 0018's own header records that
//! this table was schema-only; it is no longer, but it is also not complete,
//! and `docs/status.md` is the record of which types are live.
//!
//! # The row is written in the same transaction as the state change
//!
//! Not afterwards, and not by a trigger. An event committed separately from
//! the transition it describes is either a webhook for something that did
//! not happen (the transition rolled back) or a transition no merchant is
//! ever told about (the event write failed) — and the second is the one that
//! actually happens, because it is the failure nothing retries. So
//! [`insert_in_tx`] takes a connection, never a pool, and there is
//! deliberately no pooled variant.
//!
//! # Fan-out reads, but does not yet exist
//!
//! [`pending_page`] is the backlog query Step 5's delivery loop runs. It is
//! implemented and tested here because the settlement transaction's whole
//! claim — "a terminal transition leaves exactly one deliverable event" — is
//! only checkable by reading the backlog the way the deliverer will. Nothing
//! in a shipping binary calls it yet, and nothing marks an event `done`:
//! that writer belongs to the step that can also deliver it.

use sqlx::{PgConnection, PgPool};
use time::OffsetDateTime;

use crate::error::{DbError, classify_write};

/// The `evt_…` id minter, re-exported from `vpay_core::ids`.
///
/// Re-exported rather than left to each caller to find, because the id has
/// to be generated by the *caller* — [`insert_in_tx`] and the settlement
/// transaction both take one as an argument, so a retried settlement can
/// reuse the id it already logged instead of minting a second name for one
/// event — and a caller reaching for "some unique string" is how a table
/// whose ids merchants dedupe on (`docs/flows/webhooks.md`) acquires a row
/// with a UUID in it. The vocabulary stays closed in `vpay-core`; this is
/// only a signpost to it.
pub use vpay_core::ids::event_id;

/// Every column of `events`, in one place so the two queries cannot drift on
/// what [`EventRow`] decodes.
const COLUMNS: &str = "id, seq, merchant_id, livemode, type AS event_type, object_id, data, \
                       fanout_state, created_at";

/// One `events` row, exactly as stored.
#[derive(Debug, Clone, PartialEq, sqlx::FromRow)]
pub struct EventRow {
    /// The `evt_…` id merchants dedupe deliveries on.
    pub id: String,
    /// Fan-out order (migration 0018). Database-generated.
    pub seq: i64,
    /// Who the event belongs to. Copied from the object at emit time, not
    /// joined — see [`NewEvent::merchant_id`].
    pub merchant_id: String,
    /// Live or test money, copied from the object for the same reason.
    pub livemode: bool,
    /// One of the seven types `type_is_a_documented_event` allows. Named
    /// `event_type` because `type` is a Rust keyword; the column is `type`,
    /// which `COLUMNS` aliases rather than renaming the field with a
    /// `#[sqlx(rename)]` — the alias keeps the two queries and this struct
    /// agreeing in one place instead of two.
    pub event_type: String,
    /// The object this event is about (`pi_…`, `ch_…`, `re_…`).
    pub object_id: String,
    /// The wire object as it was when the event happened — a snapshot, so a
    /// delivery that succeeds an hour later still describes the transition
    /// it is reporting rather than whatever is true by then.
    pub data: serde_json::Value,
    /// `pending` until fan-out completes. Step 5 owns the writer that moves
    /// it; nothing does today.
    pub fanout_state: String,
    /// When the event was emitted.
    pub created_at: OffsetDateTime,
}

/// The columns a caller supplies: [`EventRow`] minus the three the database
/// owns (`seq`, `created_at`) or defaults (`fanout_state`, always `pending`
/// at insert — an event that is born `done` is an event nobody delivers).
#[derive(Debug, Clone, PartialEq)]
pub struct NewEvent {
    /// `evt_…`, from [`event_id`], generated by the caller.
    pub id: String,
    /// The merchant this event will be delivered to. Denormalised onto the
    /// row rather than reached by joining the object, because fan-out reads
    /// the backlog by `seq` alone and must not have to know which of three
    /// tables `object_id` points into to work out where to send it.
    pub merchant_id: String,
    /// From the object, never from configuration read at delivery time: a
    /// deployment's `livemode` can change between emit and delivery, and the
    /// event describes what was true when it happened.
    pub livemode: bool,
    /// One of the seven documented types. The database refuses the rest.
    pub event_type: String,
    /// The id of the object the event is about.
    pub object_id: String,
    /// The wire object, which must be a JSON object (`data_is_object`).
    pub data: serde_json::Value,
}

/// Appends one event **inside the caller's transaction**.
///
/// See the module comment for why there is no pooled variant.
///
/// # Errors
///
/// [`DbError::UniqueViolation`] on `events_pkey` if the `id` has already
/// been emitted — which for a retried settlement is the *correct* refusal:
/// two rows would be two deliveries of one transition. [`DbError::Query`]
/// otherwise, including a `type` outside the documented seven or a `data`
/// that is not a JSON object, both of which are vpay bugs.
pub async fn insert_in_tx(tx: &mut PgConnection, new: &NewEvent) -> Result<EventRow, DbError> {
    let sql = format!(
        "INSERT INTO events (id, merchant_id, livemode, type, object_id, data) \
         VALUES ($1, $2, $3, $4, $5, $6) \
         RETURNING {COLUMNS}"
    );

    sqlx::query_as::<_, EventRow>(&sql)
        .bind(&new.id)
        .bind(&new.merchant_id)
        .bind(new.livemode)
        .bind(&new.event_type)
        .bind(&new.object_id)
        .bind(&new.data)
        .fetch_one(&mut *tx)
        .await
        .map_err(classify_write)
}

/// The oldest undelivered events, in emission order, at most `limit` of
/// them.
///
/// Ordered by `seq` and not by `created_at`: two events emitted inside the
/// same microsecond tie on a timestamp, and a fan-out cursor over a
/// non-total order either repeats a delivery or — the one that matters —
/// skips one entirely. `events_pending_idx` is exactly this query's
/// predicate and order, so the scan is over the *backlog* rather than over
/// the log.
///
/// Not merchant-scoped, unlike every read in [`crate::payment_intents`]:
/// this is the worker's queue, not an API surface, and a per-merchant sweep
/// would deliver in merchant order rather than in the order things happened.
/// `GET /v1/events` is a different query, and it will be merchant-scoped.
///
/// # Errors
///
/// Returns [`DbError::Query`] if the read fails.
pub async fn pending_page(pool: &PgPool, limit: i64) -> Result<Vec<EventRow>, DbError> {
    // Postgres refuses a negative LIMIT, and a zero-row page is never what a
    // caller means.
    let limit = limit.max(1);
    let sql = format!(
        "SELECT {COLUMNS} FROM events WHERE fanout_state = 'pending' ORDER BY seq LIMIT $1"
    );

    sqlx::query_as::<_, EventRow>(&sql)
        .bind(limit)
        .fetch_all(pool)
        .await
        .map_err(DbError::Query)
}
