apiVersion: v2
name: vpay
description: vpay payment gateway — API server and background worker
type: application
version: 0.1.1
appVersion: 0.1.0
kubeVersion: '>=1.27.0-0'
home: https://github.com/vaam-apps/vpay
sources:
  - https://github.com/vaam-apps/vpay
keywords:
  - payments
  - mobile-money
