[package]
name = "vpay-tests-integration"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]

[dev-dependencies]
vpay-core.workspace = true
vpay-provider.workspace = true
vpay-adapter-mtn-momo.workspace = true
vpay-adapter-orange-money.workspace = true
vpay-testkit.workspace = true
tokio.workspace = true
rstest.workspace = true
