// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

// Hand-added after generation (2026-09-14): see ShowCheckoutRequest.toString.
import '../redaction.dart';

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Which of the two signals `checkout_controller.dart` polls will resolve
/// happened. Never a `succeeded`/`canceled`/`failed` member — the design's
/// whole point (D1) is that this interface cannot say that, only Dart's
/// poll of `/v1/browser/payment_intents/{id}` can.
enum CheckoutWindowOutcome {
  /// An **incoming deep link** (Android App Link, iOS/macOS Universal
  /// Link) matched one of `ShowCheckoutRequest.stopUrls`, bringing the app
  /// back to the foreground.
  ///
  /// **Unverified on every platform** as of 2026-09-16, and the status
  /// pages say so: a verified App Link/Universal Link needs an HTTPS
  /// origin serving `assetlinks.json` / `apple-app-site-association` for
  /// the merchant's own `success_url` host, which this repository can
  /// neither deploy nor prove against. Every host below therefore reports
  /// [dismissed] in practice today, and D1/D4 make that
  /// correctness-complete — the poll, not the window, decides. Nothing
  /// here pretends otherwise.
  stopUrlReached,

  /// The payer closed the browser sheet (back press, swipe, "Done") with
  /// no matching deep link having arrived. Since D5's 2026-09-16 revision
  /// this is the **ordinary** end of a successful payment too, not only a
  /// cancellation — which is exactly why D4 polls before answering.
  dismissed,
}

/// One stop URL, already normalised the way `checkout_controller.dart`'s
/// `StopUrlSpec` is: scheme, host, port and path only. Query and fragment
/// are ignored (D2), so they are not carried across the channel at all —
/// there is nothing here for a platform host to compare against them by
/// mistake.
class CheckoutStopUrl {
  CheckoutStopUrl({
    required this.scheme,
    required this.host,
    required this.port,
    required this.path,
  });

  String scheme;

  String host;

  int port;

  String path;

  List<Object?> _toList() {
    return <Object?>[scheme, host, port, path];
  }

  Object encode() {
    return _toList();
  }

  static CheckoutStopUrl decode(Object result) {
    result as List<Object?>;
    return CheckoutStopUrl(
      scheme: result[0]! as String,
      host: result[1]! as String,
      port: result[2]! as int,
      path: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CheckoutStopUrl || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(scheme, other.scheme) &&
        _deepEquals(host, other.host) &&
        _deepEquals(port, other.port) &&
        _deepEquals(path, other.path);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CheckoutStopUrl(scheme: $scheme, host: $host, port: $port, path: $path)';
  }
}

/// What `show` hands the platform host.
///
/// `stopUrls` is empty exactly when the session carries no `success_url` or
/// `cancel_url` at all — an embedded session never reaches here (D2 refuses
/// it at the pre-flight), but a hosted session that only ever forwards one
/// way is real and the platform host must not require both.
class ShowCheckoutRequest {
  ShowCheckoutRequest({
    required this.url,
    required this.stopUrls,
    required this.allowInsecureUrl,
  });

  /// The session's own hosted `url` (D6: carries the session secret in its
  /// fragment). The platform host loads exactly this and nothing else — it
  /// does not construct a URL of its own.
  String url;

  /// The host matches an **incoming deep link** against these (D2:
  /// scheme+host+port+path, query and fragment ignored). It no longer
  /// matches navigations: since D5 was revised on 2026-09-16 the page runs
  /// in the browser's own process, where no host on any platform can see a
  /// navigation at all. See [CheckoutWindowOutcome.stopUrlReached].
  List<CheckoutStopUrl?> stopUrls;

  /// D6's named insecure opt-in, forwarded so a platform host does not have
  /// to re-derive "is this the demo stack" from the URL's scheme itself.
  bool allowInsecureUrl;

  List<Object?> _toList() {
    return <Object?>[url, stopUrls, allowInsecureUrl];
  }

  Object encode() {
    return _toList();
  }

  static ShowCheckoutRequest decode(Object result) {
    result as List<Object?>;
    return ShowCheckoutRequest(
      url: result[0]! as String,
      stopUrls: (result[1]! as List<Object?>).cast<CheckoutStopUrl?>(),
      allowInsecureUrl: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ShowCheckoutRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(url, other.url) &&
        _deepEquals(stopUrls, other.stopUrls) &&
        _deepEquals(allowInsecureUrl, other.allowInsecureUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  /// **Hand-edited after generation (2026-09-14), and it must stay edited.**
  ///
  /// Pigeon generates `'… url: $url …'` here. [url] is the session's own
  /// hosted URL, whose fragment *is* the checkout session's `client_secret`
  /// (D6) — so the generated form renders a live credential into whatever
  /// printed it: a `debugPrint` of the request, a Flutter error dump that
  /// quotes its arguments, a crash reporter's breadcrumb. The design doc
  /// named this exact regression path: "a `copyWith`-style data class with
  /// a generated `toString` is not [safe], and generated code is how this
  /// regresses."
  ///
  /// `dart run pigeon --input pigeons/checkout.dart` overwrites this file
  /// and will undo it. `test/messages_redaction_test.dart` fails when that
  /// happens; re-apply it here and in the Kotlin and Swift copies rather
  /// than relaxing the test. It regressed for real on 2026-09-16, when the
  /// D5 browser cutover regenerated all four copies at once — the test
  /// caught all four, which is the whole reason it exists.
  @override
  String toString() {
    return 'ShowCheckoutRequest(url: ${redacted(url)}, stopUrls: $stopUrls, '
        'allowInsecureUrl: $allowInsecureUrl)';
  }
}

/// One event the platform host reports back through
/// [VpayCheckoutFlutterApi.onWindowEvent].
class CheckoutWindowEvent {
  CheckoutWindowEvent({required this.outcome, this.reachedUrl});

  CheckoutWindowOutcome outcome;

  /// The full navigated-to URL, present only for
  /// [CheckoutWindowOutcome.stopUrlReached] — carried for diagnostics only;
  /// `checkout_controller.dart` does not read anything off it (D1).
  String? reachedUrl;

  List<Object?> _toList() {
    return <Object?>[outcome, reachedUrl];
  }

  Object encode() {
    return _toList();
  }

  static CheckoutWindowEvent decode(Object result) {
    result as List<Object?>;
    return CheckoutWindowEvent(
      outcome: result[0]! as CheckoutWindowOutcome,
      reachedUrl: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CheckoutWindowEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outcome, other.outcome) &&
        _deepEquals(reachedUrl, other.reachedUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  /// **Hand-edited after generation (2026-09-14)** — see
  /// [ShowCheckoutRequest.toString]. [reachedUrl] is the full URL the deep
  /// link carried, merchant query string and all; this package never reads
  /// anything off it (D1) and has no business rendering it either.
  @override
  String toString() {
    return 'CheckoutWindowEvent(outcome: $outcome, reachedUrl: '
        '${redacted(reachedUrl)})';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CheckoutWindowOutcome) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CheckoutStopUrl) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is ShowCheckoutRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is CheckoutWindowEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : CheckoutWindowOutcome.values[value];
      case 130:
        return CheckoutStopUrl.decode(readValue(buffer)!);
      case 131:
        return ShowCheckoutRequest.decode(readValue(buffer)!);
      case 132:
        return CheckoutWindowEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart calls into the platform host. One `show`, one `dismiss` — the
/// window's entire vocabulary (design doc, "The shape").
class VpayCheckoutHostApi {
  /// Constructor for [VpayCheckoutHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VpayCheckoutHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Opens the payer's **browser** on `request.url` — a partial (bottom
  /// sheet) Custom Tab on Android, a detented `SFSafariViewController` on
  /// iOS, `NSWorkspace.open` on macOS, `window.open` on web (D5, revised
  /// 2026-09-16). Resolves once the window is showing; the outcome arrives
  /// later, over [VpayCheckoutFlutterApi.onWindowEvent].
  ///
  /// No host renders the page in a `WebView`/`WKWebView` any more. That
  /// was the previous D5 and it put vpay's payment form inside the
  /// merchant app's own process, where `evaluateJavascript`, the cookie
  /// store and a navigation delegate are all reachable — i.e. where a
  /// compromised merchant app could read the payer's PAN and OTP without
  /// the payer being able to tell. The browser's process cannot be
  /// inspected that way, and the payer gets a real URL bar. The cost is
  /// stated rather than hidden: no host can see a navigation any more, so
  /// stop URLs arrive only as deep links — see
  /// [CheckoutWindowOutcome.stopUrlReached].
  Future<void> show(ShowCheckoutRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.vpay_checkout_flutter.VpayCheckoutHostApi.show$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Closes the window if one is open. A no-op if none is.
  Future<void> dismiss() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.vpay_checkout_flutter.VpayCheckoutHostApi.dismiss$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// The platform host calls back into Dart.
abstract class VpayCheckoutFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Fired exactly once per `show`, with the one outcome that occurred.
  void onWindowEvent(CheckoutWindowEvent event);

  static void setUp(
    VpayCheckoutFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.vpay_checkout_flutter.VpayCheckoutFlutterApi.onWindowEvent$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CheckoutWindowEvent arg_event = args[0]! as CheckoutWindowEvent;
          try {
            api.onWindowEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
