[package]
name = "vpay-server"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
vpay-core.workspace = true
vpay-config.workspace = true
vpay-provider.workspace = true
vpay-adapter-mtn-momo.workspace = true
vpay-adapter-orange-money.workspace = true
vpay-api.workspace = true
vpay-worker.workspace = true
tokio.workspace = true
axum.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
mimalloc.workspace = true

[dev-dependencies]
vpay-testkit.workspace = true
