// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Which of the two signals `checkout_controller.dart` polls will resolve
/// happened. Never a `succeeded`/`canceled`/`failed` member — the design's
/// whole point (D1) is that this interface cannot say that, only Dart's
/// poll of `/v1/browser/payment_intents/{id}` can.
enum CheckoutWindowOutcome: Int, CaseIterable {
  /// An **incoming deep link** (Android App Link, iOS/macOS Universal
  /// Link) matched one of `ShowCheckoutRequest.stopUrls`, bringing the app
  /// back to the foreground.
  ///
  /// **Unverified on every platform** as of 2026-09-16, and the status
  /// pages say so: a verified App Link/Universal Link needs an HTTPS
  /// origin serving `assetlinks.json` / `apple-app-site-association` for
  /// the merchant's own `success_url` host, which this repository can
  /// neither deploy nor prove against. Every host below therefore reports
  /// [dismissed] in practice today, and D1/D4 make that
  /// correctness-complete — the poll, not the window, decides. Nothing
  /// here pretends otherwise.
  case stopUrlReached = 0
  /// The payer closed the browser sheet (back press, swipe, "Done") with
  /// no matching deep link having arrived. Since D5's 2026-09-16 revision
  /// this is the **ordinary** end of a successful payment too, not only a
  /// cancellation — which is exactly why D4 polls before answering.
  case dismissed = 1
}

/// One stop URL, already normalised the way `checkout_controller.dart`'s
/// `StopUrlSpec` is: scheme, host, port and path only. Query and fragment
/// are ignored (D2), so they are not carried across the channel at all —
/// there is nothing here for a platform host to compare against them by
/// mistake.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CheckoutStopUrl: Hashable, CustomStringConvertible {
  var scheme: String
  var host: String
  var port: Int64
  var path: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CheckoutStopUrl? {
    let scheme = pigeonVar_list[0] as! String
    let host = pigeonVar_list[1] as! String
    let port = pigeonVar_list[2] as! Int64
    let path = pigeonVar_list[3] as! String

    return CheckoutStopUrl(
      scheme: scheme,
      host: host,
      port: port,
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      scheme,
      host,
      port,
      path,
    ]
  }
  static func == (lhs: CheckoutStopUrl, rhs: CheckoutStopUrl) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.scheme, rhs.scheme) && MessagesPigeonInternal.deepEquals(lhs.host, rhs.host) && MessagesPigeonInternal.deepEquals(lhs.port, rhs.port) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CheckoutStopUrl")
    MessagesPigeonInternal.deepHash(value: scheme, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: host, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: port, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
  }

  public var description: String {
    return "CheckoutStopUrl(scheme: \(String(describing: scheme)), host: \(String(describing: host)), port: \(String(describing: port)), path: \(String(describing: path)))"
  }
}

/// What `show` hands the platform host.
///
/// `stopUrls` is empty exactly when the session carries no `success_url` or
/// `cancel_url` at all — an embedded session never reaches here (D2 refuses
/// it at the pre-flight), but a hosted session that only ever forwards one
/// way is real and the platform host must not require both.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ShowCheckoutRequest: Hashable, CustomStringConvertible {
  /// The session's own hosted `url` (D6: carries the session secret in its
  /// fragment). The platform host loads exactly this and nothing else — it
  /// does not construct a URL of its own.
  var url: String
  /// The host matches an **incoming deep link** against these (D2:
  /// scheme+host+port+path, query and fragment ignored). It no longer
  /// matches navigations: since D5 was revised on 2026-09-16 the page runs
  /// in the browser's own process, where no host on any platform can see a
  /// navigation at all. See [CheckoutWindowOutcome.stopUrlReached].
  var stopUrls: [CheckoutStopUrl?]
  /// D6's named insecure opt-in, forwarded so a platform host does not have
  /// to re-derive "is this the demo stack" from the URL's scheme itself.
  var allowInsecureUrl: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ShowCheckoutRequest? {
    let url = pigeonVar_list[0] as! String
    let stopUrls = pigeonVar_list[1] as! [CheckoutStopUrl?]
    let allowInsecureUrl = pigeonVar_list[2] as! Bool

    return ShowCheckoutRequest(
      url: url,
      stopUrls: stopUrls,
      allowInsecureUrl: allowInsecureUrl
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      stopUrls,
      allowInsecureUrl,
    ]
  }
  static func == (lhs: ShowCheckoutRequest, rhs: ShowCheckoutRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.url, rhs.url) && MessagesPigeonInternal.deepEquals(lhs.stopUrls, rhs.stopUrls) && MessagesPigeonInternal.deepEquals(lhs.allowInsecureUrl, rhs.allowInsecureUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ShowCheckoutRequest")
    MessagesPigeonInternal.deepHash(value: url, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stopUrls, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: allowInsecureUrl, hasher: &hasher)
  }

  /// Hand-edited after generation (2026-09-14), and it must stay edited:
  /// `url`'s fragment is the checkout session's own `client_secret` (design
  /// doc D6), and the generated form would render it into any `print`, `os_log`
  /// or crash-reporter breadcrumb. Regenerating this file undoes it — it did,
  /// on 2026-09-16, when the D5 browser cutover regenerated all four copies at
  /// once; re-apply it here and in the Dart and Kotlin copies. The Dart copy is
  /// the one under test (`test/messages_redaction_test.dart`); this one is not
  /// compiled by any test in this repository.
  public var description: String {
    return "ShowCheckoutRequest(url: [\(url.count) chars redacted], stopUrls: \(String(describing: stopUrls)), allowInsecureUrl: \(String(describing: allowInsecureUrl)))"
  }
}

/// One event the platform host reports back through
/// [VpayCheckoutFlutterApi.onWindowEvent].
///
/// Generated class from Pigeon that represents data sent in messages.
struct CheckoutWindowEvent: Hashable, CustomStringConvertible {
  var outcome: CheckoutWindowOutcome
  /// The full navigated-to URL, present only for
  /// [CheckoutWindowOutcome.stopUrlReached] — carried for diagnostics only;
  /// `checkout_controller.dart` does not read anything off it (D1).
  var reachedUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CheckoutWindowEvent? {
    let outcome = pigeonVar_list[0] as! CheckoutWindowOutcome
    let reachedUrl: String? = nilOrValue(pigeonVar_list[1])

    return CheckoutWindowEvent(
      outcome: outcome,
      reachedUrl: reachedUrl
    )
  }
  func toList() -> [Any?] {
    return [
      outcome,
      reachedUrl,
    ]
  }
  static func == (lhs: CheckoutWindowEvent, rhs: CheckoutWindowEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.outcome, rhs.outcome) && MessagesPigeonInternal.deepEquals(lhs.reachedUrl, rhs.reachedUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CheckoutWindowEvent")
    MessagesPigeonInternal.deepHash(value: outcome, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: reachedUrl, hasher: &hasher)
  }

  /// Hand-edited after generation (2026-09-14) — see
  /// `ShowCheckoutRequest.description`.
  public var description: String {
    let redactedUrl = reachedUrl.map { "[\($0.count) chars redacted]" } ?? "null"
    return "CheckoutWindowEvent(outcome: \(String(describing: outcome)), reachedUrl: \(redactedUrl))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CheckoutWindowOutcome(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return CheckoutStopUrl.fromList(self.readValue() as! [Any?])
    case 131:
      return ShowCheckoutRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return CheckoutWindowEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CheckoutWindowOutcome {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CheckoutStopUrl {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ShowCheckoutRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CheckoutWindowEvent {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Dart calls into the platform host. One `show`, one `dismiss` — the
/// window's entire vocabulary (design doc, "The shape").
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VpayCheckoutHostApi {
  /// Opens the payer's **browser** on `request.url` — a partial (bottom
  /// sheet) Custom Tab on Android, a detented `SFSafariViewController` on
  /// iOS, `NSWorkspace.open` on macOS, `window.open` on web (D5, revised
  /// 2026-09-16). Resolves once the window is showing; the outcome arrives
  /// later, over [VpayCheckoutFlutterApi.onWindowEvent].
  ///
  /// No host renders the page in a `WebView`/`WKWebView` any more. That
  /// was the previous D5 and it put vpay's payment form inside the
  /// merchant app's own process, where `evaluateJavascript`, the cookie
  /// store and a navigation delegate are all reachable — i.e. where a
  /// compromised merchant app could read the payer's PAN and OTP without
  /// the payer being able to tell. The browser's process cannot be
  /// inspected that way, and the payer gets a real URL bar. The cost is
  /// stated rather than hidden: no host can see a navigation any more, so
  /// stop URLs arrive only as deep links — see
  /// [CheckoutWindowOutcome.stopUrlReached].
  func show(request: ShowCheckoutRequest) async throws
  /// Closes the window if one is open. A no-op if none is.
  func dismiss() async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VpayCheckoutHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VpayCheckoutHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VpayCheckoutHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Opens the payer's **browser** on `request.url` — a partial (bottom
    /// sheet) Custom Tab on Android, a detented `SFSafariViewController` on
    /// iOS, `NSWorkspace.open` on macOS, `window.open` on web (D5, revised
    /// 2026-09-16). Resolves once the window is showing; the outcome arrives
    /// later, over [VpayCheckoutFlutterApi.onWindowEvent].
    ///
    /// No host renders the page in a `WebView`/`WKWebView` any more. That
    /// was the previous D5 and it put vpay's payment form inside the
    /// merchant app's own process, where `evaluateJavascript`, the cookie
    /// store and a navigation delegate are all reachable — i.e. where a
    /// compromised merchant app could read the payer's PAN and OTP without
    /// the payer being able to tell. The browser's process cannot be
    /// inspected that way, and the payer gets a real URL bar. The cost is
    /// stated rather than hidden: no host can see a navigation any more, so
    /// stop URLs arrive only as deep links — see
    /// [CheckoutWindowOutcome.stopUrlReached].
    let showChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpay_checkout_flutter.VpayCheckoutHostApi.show\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ShowCheckoutRequest
        Task { @MainActor in
          do {
            try await api.show(request: requestArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      showChannel.setMessageHandler(nil)
    }
    /// Closes the window if one is open. A no-op if none is.
    let dismissChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpay_checkout_flutter.VpayCheckoutHostApi.dismiss\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      dismissChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.dismiss()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      dismissChannel.setMessageHandler(nil)
    }
  }
}

/// The platform host calls back into Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VpayCheckoutFlutterApiProtocol {
  /// Fired exactly once per `show`, with the one outcome that occurred.
  @MainActor func onWindowEvent(event eventArg: CheckoutWindowEvent) async throws
}
class VpayCheckoutFlutterApi: VpayCheckoutFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// Fired exactly once per `show`, with the one outcome that occurred.
  @MainActor func onWindowEvent(event eventArg: CheckoutWindowEvent) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.vpay_checkout_flutter.VpayCheckoutFlutterApi.onWindowEvent\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
