// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.vpay.checkout_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * D8: which window the platform host shows. Mirrors
 * `vpay_checkout.dart`'s `VpayCheckoutMode` — the two enums are kept
 * distinct on purpose (one is the public Dart API, one is a wire type) so
 * the pigeon-generated side can change shape without touching the public
 * one, but every member here must have a same-named counterpart there.
 */
enum class CheckoutWindowMode(val raw: Int) {
  /** The in-app `WebView`/`WKWebView`/popup (design doc D5). */
  IN_APP(0),
  /**
   * Custom Tabs on Android, `SFSafariViewController` on iOS below 17.4
   * (design doc D8) — no custom URL scheme, ever (D8: schemes are
   * first-come-first-served on Android and any installed app could claim
   * one).
   */
  EXTERNAL_BROWSER(1);

  companion object {
    fun ofRaw(raw: Int): CheckoutWindowMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Which of the two signals `checkout_controller.dart` polls will resolve
 * happened. Never a `succeeded`/`canceled`/`failed` member — the design's
 * whole point (D1) is that this interface cannot say that, only Dart's
 * poll of `/v1/browser/payment_intents/{id}` can.
 */
enum class CheckoutWindowOutcome(val raw: Int) {
  /** A navigation matched one of `ShowCheckoutRequest.stopUrls`. */
  STOP_URL_REACHED(0),
  /**
   * The payer dismissed the window (back press, swipe, close) without a
   * navigation ever matching a stop URL.
   */
  DISMISSED(1);

  companion object {
    fun ofRaw(raw: Int): CheckoutWindowOutcome? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * One stop URL, already normalised the way `checkout_controller.dart`'s
 * `StopUrlSpec` is: scheme, host, port and path only. Query and fragment
 * are ignored (D2), so they are not carried across the channel at all —
 * there is nothing here for a platform host to compare against them by
 * mistake.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CheckoutStopUrl (
  val scheme: String,
  val host: String,
  val port: Long,
  val path: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CheckoutStopUrl {
      val scheme = pigeonVar_list[0] as String
      val host = pigeonVar_list[1] as String
      val port = pigeonVar_list[2] as Long
      val path = pigeonVar_list[3] as String
      return CheckoutStopUrl(scheme, host, port, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      scheme,
      host,
      port,
      path,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CheckoutStopUrl
    return MessagesPigeonUtils.deepEquals(this.scheme, other.scheme) && MessagesPigeonUtils.deepEquals(this.host, other.host) && MessagesPigeonUtils.deepEquals(this.port, other.port) && MessagesPigeonUtils.deepEquals(this.path, other.path)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.scheme)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.host)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.port)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.path)
    return result
  }
  override fun toString(): String {
    return "CheckoutStopUrl(scheme=$scheme, host=$host, port=$port, path=$path)"
  }
}

/**
 * What `show` hands the platform host.
 *
 * `stopUrls` is empty exactly when the session carries no `success_url` or
 * `cancel_url` at all — an embedded session never reaches here (D2 refuses
 * it at the pre-flight), but a hosted session that only ever forwards one
 * way is real and the platform host must not require both.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ShowCheckoutRequest (
  /**
   * The session's own hosted `url` (D6: carries the session secret in its
   * fragment). The platform host loads exactly this and nothing else — it
   * does not construct a URL of its own.
   */
  val url: String,
  val stopUrls: List<CheckoutStopUrl?>,
  /**
   * D6's named insecure opt-in, forwarded so a platform host does not have
   * to re-derive "is this the demo stack" from the URL's scheme itself.
   */
  val allowInsecureUrl: Boolean,
  /**
   * D8: `inApp` (the default) or `externalBrowser`. A platform host that
   * has not implemented `externalBrowser` refuses rather than silently
   * falling back to `inApp` — see `vpay_checkout.dart`'s doc comment on
   * `VpayCheckoutMode.externalBrowser` for why that fallback is the worse
   * failure.
   */
  val mode: CheckoutWindowMode
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ShowCheckoutRequest {
      val url = pigeonVar_list[0] as String
      val stopUrls = pigeonVar_list[1] as List<CheckoutStopUrl?>
      val allowInsecureUrl = pigeonVar_list[2] as Boolean
      val mode = pigeonVar_list[3] as CheckoutWindowMode
      return ShowCheckoutRequest(url, stopUrls, allowInsecureUrl, mode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      stopUrls,
      allowInsecureUrl,
      mode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ShowCheckoutRequest
    return MessagesPigeonUtils.deepEquals(this.url, other.url) && MessagesPigeonUtils.deepEquals(this.stopUrls, other.stopUrls) && MessagesPigeonUtils.deepEquals(this.allowInsecureUrl, other.allowInsecureUrl) && MessagesPigeonUtils.deepEquals(this.mode, other.mode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.url)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.stopUrls)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.allowInsecureUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mode)
    return result
  }
  /**
   * Hand-edited after generation (2026-09-14), and it must stay edited: `url`'s
   * fragment is the checkout session's own `client_secret` (design doc D6), and
   * Kotlin's generated `toString` would render it into any `Log.d(TAG, request)`
   * or crash-reporter breadcrumb. Regenerating this file undoes it; re-apply it
   * here and in the Dart and Swift copies. The Dart copy is the one under test
   * (`test/messages_redaction_test.dart`); this one is not compiled by any test
   * in this repository.
   */
  override fun toString(): String {
    return "ShowCheckoutRequest(url=[${url.length} chars redacted], stopUrls=$stopUrls, allowInsecureUrl=$allowInsecureUrl, mode=$mode)"
  }
}

/**
 * One event the platform host reports back through
 * [VpayCheckoutFlutterApi.onWindowEvent].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CheckoutWindowEvent (
  val outcome: CheckoutWindowOutcome,
  /**
   * The full navigated-to URL, present only for
   * [CheckoutWindowOutcome.stopUrlReached] — carried for diagnostics only;
   * `checkout_controller.dart` does not read anything off it (D1).
   */
  val reachedUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CheckoutWindowEvent {
      val outcome = pigeonVar_list[0] as CheckoutWindowOutcome
      val reachedUrl = pigeonVar_list[1] as String?
      return CheckoutWindowEvent(outcome, reachedUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      outcome,
      reachedUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CheckoutWindowEvent
    return MessagesPigeonUtils.deepEquals(this.outcome, other.outcome) && MessagesPigeonUtils.deepEquals(this.reachedUrl, other.reachedUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outcome)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.reachedUrl)
    return result
  }
  /** Hand-edited after generation (2026-09-14) — see [ShowCheckoutRequest.toString]. */
  override fun toString(): String {
    val redacted = reachedUrl?.let { "[${it.length} chars redacted]" } ?: "null"
    return "CheckoutWindowEvent(outcome=$outcome, reachedUrl=$redacted)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CheckoutWindowMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CheckoutWindowOutcome.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CheckoutStopUrl.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ShowCheckoutRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CheckoutWindowEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CheckoutWindowMode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is CheckoutWindowOutcome -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is CheckoutStopUrl -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ShowCheckoutRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is CheckoutWindowEvent -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart calls into the platform host. One `show`, one `dismiss` — the
 * window's entire vocabulary (design doc, "The shape").
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface VpayCheckoutHostApi {
  /**
   * Opens the native window (Android `Activity`+`WebView`, iOS/macOS
   * `UIViewController`/`NSViewController`+`WKWebView`, or `window.open` on
   * web — D5) loading `request.url`. Resolves once the window is showing;
   * the outcome arrives later, over [VpayCheckoutFlutterApi.onWindowEvent].
   */
  suspend fun show(request: ShowCheckoutRequest)
  /** Closes the window if one is open. A no-op if none is. */
  suspend fun dismiss()

  companion object {
    /** The codec used by VpayCheckoutHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `VpayCheckoutHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VpayCheckoutHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpay_checkout_flutter.VpayCheckoutHostApi.show$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ShowCheckoutRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.show(requestArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpay_checkout_flutter.VpayCheckoutHostApi.dismiss$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.dismiss()
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * The platform host calls back into Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class VpayCheckoutFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VpayCheckoutFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /** Fired exactly once per `show`, with the one outcome that occurred. */
  suspend fun onWindowEvent(eventArg: CheckoutWindowEvent)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.vpay_checkout_flutter.VpayCheckoutFlutterApi.onWindowEvent$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
